### PR TITLE
Lab2 part4

### PR DESCRIPTION
**Pull request by sding3**
[Lab-Assignment-2](https://canvas.wisc.edu/courses/155029/assignments/675609)

> ## **Part 4: Mininet live testing**
> 
> In this section you will test your router code from Part 1 and Part 2 of the assignment on a live mininet topology. **NOTE:** Use the start_mininet.py file which we have provided in the downloads.

>1.  Instructions to test for Part 1 are given here - [arp mininet (Links to an external site.)](https://github.com/jsommers/switchyard/blob/master/examples/exercises/router/router1.rst#mininet-live-testing). Once you do the experiment capture the output of **“ping -c3 10.1.1.2”** on wireshark, save the capture to an output file called **part1_ping.pcapng**. Pcapng is the extension wireshark let’s you save. Close mininet and start the same topology again.
```bash
$ file part1_ping.pcapng
part1_ping.pcapng: pcap-ng capture file - version 1.0

$ tcpdump -r part1_ping.pcapng
reading from file part1_ping.pcapng, link-type EN10MB (Ethernet)
10:23:43.757495 ARP, Request who-has 10.1.1.2 tell 10.1.1.1, length 28
10:23:43.849508 ARP, Reply 10.1.1.2 is-at 40:00:00:00:00:03 (oui Unknown), length 28
10:23:43.849520 IP 10.1.1.1 > 10.1.1.2: ICMP echo request, id 3294, seq 1, length 64
10:23:44.766406 IP 10.1.1.1 > 10.1.1.2: ICMP echo request, id 3294, seq 2, length 64
10:23:45.774245 IP 10.1.1.1 > 10.1.1.2: ICMP echo request, id 3294, seq 3, length 64

```
>2. Now instead of sending ping -c3 10.1.1.2 from the client, you should sne **“arping -c3 10.1.1.2”**. The output of the wireshark capture should be saved to **part1_arping.pcapng.**
```bash
$ file part1_arping.pcapng
part1_arping.pcapng: pcap-ng capture file - version 1.0

$ tcpdump -r part1_arping.pcapng
reading from file part1_arping.pcapng, link-type EN10MB (Ethernet)
10:42:08.688524 ARP, Request who-has 10.1.1.2 (Broadcast) tell 10.1.1.1, length 28
10:42:08.751078 ARP, Reply 10.1.1.2 is-at 40:00:00:00:00:03 (oui Unknown), length 28
10:42:09.688664 ARP, Request who-has 10.1.1.2 (40:00:00:00:00:03 (oui Unknown)) tell 10.1.1.1, length 28
10:42:09.747174 ARP, Reply 10.1.1.2 is-at 40:00:00:00:00:03 (oui Unknown), length 28
10:42:10.689496 ARP, Request who-has 10.1.1.2 (40:00:00:00:00:03 (oui Unknown)) tell 10.1.1.1, length 28
10:42:10.747278 ARP, Reply 10.1.1.2 is-at 40:00:00:00:00:03 (oui Unknown), length 28

```
>3. Instructions to test for Part 2 are given here - [routing_mininet (Links to an external site.)](https://github.com/jsommers/switchyard/blob/master/examples/exercises/router/router2.rst#mininet-live-testing). Once you do the experiment capture the output of **“ping -c2 198.168.100.1”** from the client while capturing packets on router-eth0 as per instructions in the link.The output of the wireshark capture should be saved to **part2_ping.pcapng.**
```bash
$ file part2_ping.pcapng
part2_ping.pcapng: pcap-ng capture file - version 1.0

$ tcpdump -r part2_ping.pcapng
reading from file part2_ping.pcapng, link-type EN10MB (Ethernet)
19:37:12.735869 ARP, Request who-has 192.168.100.1 (Broadcast) tell 192.168.100.2, length 28
19:37:12.735887 ARP, Reply 192.168.100.1 is-at 10:00:00:00:00:01 (oui Unknown), length 28
19:37:12.831478 IP 10.1.1.1 > 192.168.100.1: ICMP echo request, id 7267, seq 1, length 64
19:37:12.831515 IP 192.168.100.1 > 10.1.1.1: ICMP echo reply, id 7267, seq 1, length 64
19:37:13.733307 IP 10.1.1.1 > 192.168.100.1: ICMP echo request, id 7267, seq 2, length 64
19:37:13.733332 IP 192.168.100.1 > 10.1.1.1: ICMP echo reply, id 7267, seq 2, length 64
```

### CODE REVIEW

**Comment by dmbillmireUW** [comment]
I think this should work best if we run it on part3 once that's complete. I'm not sure if we're getting the expected output for part2 testing.

**Comment by sding3** [comment]
> I think this should work best if we run it on part3 once that's complete. I'm not sure if we're getting the expected output for part2 testing.

So, this section of lab2 doesn't actually do anything with part3. It only requires packet captures against our solutions for part1 and part2.

**Comment by sding3** [comment]
>I'm not sure if we're getting the expected output for part2 testing.

Could you elaborate on this point ?

**Comment by dmbillmireUW** [comment]
I was misunderstanding how part4 was supposed to work -- I see now that it doesn't depend on part3.

However I did find a bug (now fixed) in my original version of part2 that partially broke ARP handling, so if part 4.2 is dependent on that working smoothly then we should re-run it.

**Comment by sding3** [comment]
> However I did find a bug (now fixed) in my original version of part2 that partially broke ARP handling, so if part 4.2 is dependent on that working smoothly then we should re-run it.

Yep, I knew about that one, but never gotten around in putting in a comment about it. I had fixed that in a local copy before I had ran the capture.

**Comment by sding3** [comment]
Added new part2_ping.pcapng

```
19:04:11.414844 ARP, Request who-has 192.168.100.1 (Broadcast) tell 192.168.100.2, length 28
19:04:11.414858 ARP, Reply 192.168.100.1 is-at 10:00:00:00:00:01 (oui Unknown), length 28
19:04:11.518472 IP 10.1.1.1 > 192.168.100.1: ICMP echo request, id 6423, seq 1, length 64
19:04:11.518487 IP 192.168.100.1 > 10.1.1.1: ICMP echo reply, id 6423, seq 1, length 64
19:04:12.449301 IP 10.1.1.1 > 192.168.100.1: ICMP echo request, id 6423, seq 2, length 64
19:04:12.449319 IP 192.168.100.1 > 10.1.1.1: ICMP echo reply, id 6423, seq 2, length 64
19:04:16.681891 ARP, Request who-has 192.168.100.2 tell 192.168.100.1, length 28
19:04:16.716931 ARP, Reply 192.168.100.2 is-at 40:00:00:00:00:01 (oui Unknown), length 28

```

**Pull request merged**
